name: Trigger auto deployment for gh-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ harrli/test ]
    paths:
    - '**'
    - '.github/workflows/gh-test-app-AutoDeployTrigger-2344e31a-5c68-431b-aed5-bf1cd809f588.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GHTESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GHTESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GHTESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.GHTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GHTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: gh-test-app
          resourceGroup: ca-harrli-group
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


